// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RightStakes.Challenge.Infra.Data.Context;

namespace RightStakes.Challenge.Infra.Data.Migrations
{
    [DbContext(typeof(RightStakesContext))]
    partial class RightStakesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RightStakes.Challenge.Domain.Entities.CryptoCurrency", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Ath")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AthChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AthDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Atl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AtlChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AtlDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CirculatingSupply")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("FullyDilutedValuation")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("High24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Low24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("MarketCapChange24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MarketCapChangePercentage24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MarketCapRank")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxSupply")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PriceChange24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceChangePercentage24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalSupply")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TotalVolume")
                        .HasColumnType("bigint");

                    b.HasKey("Uid");

                    b.ToTable("CryptoCurrency");
                });

            modelBuilder.Entity("RightStakes.Challenge.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Uid");

                    b.ToTable("Quote");
                });
#pragma warning restore 612, 618
        }
    }
}
